volumes:
    data:

services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=123456
        ports:
            - 5432:5432
        volumes:
            - data:/var/lib/postgresql
